name: Simple CI/CD

on: [push] # This workflow will trigger on every push to the repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
