name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    name: print Repo Name
    steps:
      - name: Example variable usage
        run: echo "Repo Name"

