name: Get User Input

on: [workflow_dispatch]

jobs:
  get_input:
    runs-on: ubuntu-latest

    inputs:
      user_input:
        description: 'Enter some input'
        required: true

    steps:
      - name: Set up environment
        run: echo "Setting up environment"

      - name: Print User Input
        run: |
          # Get the user input from the workflow input
          USER_INPUT="${{ github.event.inputs.user_input }}"
          
          # Print the user input
          echo "User input is: $USER_INPUT"
